#!/usr/bin/env python3
"""Regenerate docs/00-index.md from data/. Output is generated; do not hand-edit."""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from registry import DIRS, TITLES, TYPES  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent


def load(t: str) -> list[dict]:
    d = ROOT / "data" / DIRS[t]
    if not d.exists():
        return []
    out = []
    for f in sorted(d.glob("*.json")):
        try:
            rec = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if isinstance(rec, dict):
            rec["_rid"] = f"{DIRS[t]}/{f.stem}"
            out.append(rec)
    return out


def card(r: dict) -> str:
    rid = r["_rid"]
    t = r["type"]
    if t == "accelerator":
        bits = [str(x) for x in (r.get("vendor"), r.get("architecture"), r.get("release_year")) if x]
        head = " ".join(bits) or "unspecified"
        tail = []
        if r.get("vram_gb"):
            tail.append(f"{r['vram_gb']} GB {r.get('memory_type') or ''}".strip())
        if r.get("memory_bandwidth_gbps"):
            tail.append(f"{r['memory_bandwidth_gbps']} GB/s")
        if r.get("tdp_w"):
            tail.append(f"{r['tdp_w']} W")
    elif t == "flop":
        head = f"{r.get('bound_by')} bound"
        tail = [str(r.get("arithmetic_intensity") or "")]
    elif t == "engine":
        head = ", ".join(r.get("supported_backends") or []) or "no backends listed"
        tail = ["; ".join(r.get("best_for") or [])[:200]]
    elif t == "quantization":
        head = str(r.get("bits") or "?")
        tail = [str(r.get("quality_delta") or "")]
    elif t == "interconnect":
        head = f"{r.get('bandwidth_gbps')} GB/s"
        tail = [str(r.get("topology") or "")]
    elif t == "benchmark":
        head = f"{r.get('value')} {r.get('unit') or ''}".strip()
        tail = [f"{r.get('model')} on {', '.join(r.get('accelerator_ids') or []) or '?'} via {r.get('engine_id')}"]
    elif t == "gotcha":
        head = f"[{r.get('severity')}] {r.get('class')}"
        tail = [str(r.get("symptom") or "")[:200]]
    elif t == "supply":
        bits = [str(x) for x in (r.get("vendor"), r.get("region")) if x]
        head = " · ".join(bits) or r.get("kind") or ""
        price = r.get("price_usd")
        tail = [f"${price:,}" if isinstance(price, (int, float)) else "", str(r.get("availability") or "")]
        tail = [x for x in tail if x]
        if r.get("price_basis"):
            tail.append(str(r["price_basis"])[:80])
    else:
        head = str(r.get("kind") or "")
        tail = [str(r.get("publisher") or "")]
    tail = [x for x in tail if x]
    line = f"- **{r.get('name')}** (`{rid}`)"
    if head:
        line += f" — {head}"
    if tail:
        line += " · " + " · ".join(tail)
    return line


def sort_key(r: dict):
    return (str(r.get("vendor") or r.get("kind") or r.get("bound_by")
                 or r.get("severity") or r.get("class") or ""), str(r.get("name") or ""))


def main() -> None:
    lines = [
        "# Index",
        "",
        f"<!-- GENERATED by tools/index.py on {date.today().isoformat()}. Do not hand-edit. -->",
        "",
    ]
    total = 0
    by_group: dict[str, int] = defaultdict(int)

    for t in TYPES:
        recs = load(t)
        total += len(recs)
        lines += [f"## {TITLES[t]} ({len(recs)})", ""]
        if not recs:
            lines += ["_empty — see `python tools/query.py gaps`_", ""]
            continue
        for r in sorted(recs, key=sort_key):
            lines.append(card(r))
            if t == "accelerator" and r.get("vendor"):
                by_group[f"vendor:{r['vendor']}"] += 1
            elif t == "flop" and r.get("bound_by"):
                by_group[f"flop bound:{r['bound_by']}"] += 1
            elif t == "engine":
                for b in r.get("supported_backends") or []:
                    by_group[f"backend:{b}"] += 1
            elif t == "gotcha" and r.get("severity"):
                by_group[f"severity:{r['severity']}"] += 1
        lines.append("")

    lines += ["## Coverage", "", f"Total records: **{total}**", ""]
    if by_group:
        lines += ["| group | records |", "|---|---|"]
        for k, v in sorted(by_group.items(), key=lambda x: (-x[1], x[0])):
            lines.append(f"| {k} | {v} |")
        lines.append("")

    missing = [t for t in TYPES if not load(t)]
    if missing:
        lines += ["## Gaps", ""]
        for t in missing:
            lines.append(f"- [ ] {TITLES[t]} — `data/{DIRS[t]}/` is empty")
        lines.append("")

    out = ROOT / "docs" / "00-index.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({total} records)")


if __name__ == "__main__":
    main()